import type { Subject, Student } from './types';
import { scheduleExamsGreedy } from './greedy-exam';
import { scheduleExamsGenetic } from './genetic-exam';

const subjects: Subject[] = [
  { name: 'Maths', duration: 2 },
  { name: 'Physics', duration: 2 },
  { name: 'Chemistry', duration: 4 },
  { name: 'Biology', duration: 2 },
  { name: 'History', duration: 1 },
  { name: 'Geography', duration: 1 },
  { name: 'Sculpture', duration: 2 },
  { name: 'Painting', duration: 2 },
  { name: 'Music', duration: 1 },
  { name: 'Political Science', duration: 3 },
  { name: 'Art', duration: 2 },
  { name: 'Philosophy', duration: 3 },
  { name: 'Physical Education', duration: 1 },
  { name: 'Spanish', duration: 2 },
  { name: 'Psychology', duration: 3 },
  { name: 'French', duration: 2 },
  { name: 'Literature', duration: 2 },
  { name: 'Computer Science', duration: 3 },
  { name: 'Economics', duration: 3 },
  { name: 'English', duration: 2 }
];

const students: Student[] = [
  { name: 'Student1', subjects: ['Sculpture', 'Painting', 'Music', 'Political Science', 'Art', 'Philosophy', 'Physical Education', 'Spanish'] },
  { name: 'Student2', subjects: ['Sculpture', 'Painting', 'Spanish', 'Political Science', 'Psychology'] },
  { name: 'Student3', subjects: ['Psychology', 'Sculpture', 'Spanish', 'Painting', 'French', 'Philosophy', 'Physical Education', 'Art'] },
  { name: 'Student4', subjects: ['Geography', 'Literature', 'Biology', 'Computer Science', 'Economics', 'Chemistry', 'Physics', 'History'] },
  { name: 'Student5', subjects: ['Chemistry', 'History', 'Maths', 'Literature', 'Biology', 'Geography', 'English', 'Physics'] },
  { name: 'Student6', subjects: ['Political Science', 'Music', 'Painting', 'Physical Education', 'Spanish'] },
  { name: 'Student7', subjects: ['Biology', 'Physics', 'English', 'Chemistry', 'Geography', 'Computer Science', 'Literature', 'Economics', 'History', 'Maths'] },
  { name: 'Student8', subjects: ['Painting', 'French', 'Psychology', 'Spanish'] },
  { name: 'Student9', subjects: ['Psychology', 'Music', 'Philosophy', 'Spanish', 'Physical Education', 'French', 'Political Science', 'Painting'] },
  { name: 'Student10', subjects: ['Music', 'Physical Education', 'Sculpture', 'Political Science', 'Art', 'Painting', 'Philosophy', 'French', 'Spanish'] },
  { name: 'Student11', subjects: ['Biology', 'History', 'English', 'Maths', 'Economics', 'Computer Science'] },
  { name: 'Student12', subjects: ['Maths', 'Biology', 'History', 'Geography', 'Physics', 'Literature', 'English', 'Chemistry'] },
  { name: 'Student13', subjects: ['Literature', 'Maths', 'Computer Science', 'Physics', 'Chemistry', 'Economics', 'History', 'Geography', 'English', 'Biology'] },
  { name: 'Student14', subjects: ['Sculpture', 'Literature', 'Chemistry', 'Physical Education', 'Physics', 'Art'] },
  { name: 'Student15', subjects: ['Art', 'Music', 'Sculpture', 'Philosophy', 'Psychology'] },
  { name: 'Student16', subjects: ['Painting', 'Art', 'Philosophy', 'Political Science', 'Music', 'Physical Education', 'French'] },
  { name: 'Student17', subjects: ['English', 'Geography', 'Physics', 'Biology'] },
  { name: 'Student18', subjects: ['Political Science', 'Physical Education', 'Painting', 'Sculpture', 'Spanish', 'Psychology', 'French', 'Music', 'Philosophy', 'Art'] },
  { name: 'Student19', subjects: ['Painting', 'Art', 'French', 'Spanish', 'Philosophy'] },
  { name: 'Student20', subjects: ['Political Science', 'Sculpture', 'Spanish', 'Music', 'Psychology'] },
  { name: 'Student21', subjects: ['Computer Science', 'Biology', 'Physics', 'English', 'History', 'Maths'] },
  { name: 'Student22', subjects: ['Biology', 'English', 'Chemistry'] },
  { name: 'Student23', subjects: ['History', 'Economics', 'English', 'Maths', 'Computer Science', 'Biology', 'Geography', 'Chemistry', 'Literature'] },
  { name: 'Student24', subjects: ['Philosophy', 'Psychology', 'Physical Education', 'Sculpture', 'Spanish'] },
  { name: 'Student25', subjects: ['History', 'Physics', 'Chemistry', 'Computer Science', 'Economics', 'Literature', 'Biology', 'Maths'] },
  { name: 'Student26', subjects: ['Painting', 'Psychology', 'Music', 'Physical Education', 'Sculpture', 'Political Science', 'French', 'Spanish', 'Philosophy', 'Art'] },
  { name: 'Student27', subjects: ['Economics', 'Geography', 'Maths', 'Literature', 'Chemistry', 'Computer Science', 'History', 'English'] },
  { name: 'Student28', subjects: ['English', 'Geography', 'Economics', 'Biology', 'Physics', 'History', 'Maths', 'Literature'] },
  { name: 'Student29', subjects: ['French', 'Music', 'Spanish', 'Political Science', 'Painting', 'Philosophy', 'Art', 'Physical Education'] },
  { name: 'Student30', subjects: ['Painting', 'Political Science', 'Psychology'] },
  { name: 'Student31', subjects: ['Literature', 'English', 'Economics'] },
  { name: 'Student32', subjects: ['English', 'Maths', 'Economics', 'Chemistry'] },
  { name: 'Student33', subjects: ['English', 'Computer Science', 'Geography', 'Biology', 'Economics', 'Physics', 'History', 'Chemistry'] },
  { name: 'Student34', subjects: ['Chemistry', 'History', 'Literature', 'Maths', 'Economics', 'English', 'Computer Science', 'Geography', 'Biology', 'Physics'] },
  { name: 'Student35', subjects: ['Political Science', 'Art', 'Sculpture', 'Philosophy', 'Psychology', 'Painting', 'Spanish', 'Physical Education', 'Music', 'French'] },
  { name: 'Student36', subjects: ['Physics', 'Maths', 'English', 'Biology', 'Literature', 'Economics', 'Computer Science'] },
  { name: 'Student37', subjects: ['Literature', 'Physics', 'Chemistry', 'Biology', 'Computer Science', 'Economics', 'Geography'] },
  { name: 'Student38', subjects: ['Physics', 'Literature', 'History', 'English', 'Computer Science', 'Maths'] },
  { name: 'Student39', subjects: ['Literature', 'Biology', 'Chemistry', 'Geography', 'Maths'] },
  { name: 'Student40', subjects: ['Biology', 'Music', 'Art', 'Philosophy', 'Physical Education', 'Physics', 'Spanish', 'Maths', 'Economics'] },
  { name: 'Student41', subjects: ['Psychology', 'French', 'Music'] },
  { name: 'Student42', subjects: ['French', 'Political Science', 'Spanish', 'Psychology', 'Music'] },
  { name: 'Student43', subjects: ['French', 'Spanish', 'Philosophy', 'Sculpture', 'Painting', 'Physical Education', 'Psychology'] },
  { name: 'Student44', subjects: ['Literature', 'Economics', 'Physical Education', 'Sculpture', 'History'] },
  { name: 'Student45', subjects: ['Chemistry', 'Computer Science', 'Literature', 'Maths', 'Economics', 'Geography', 'History', 'Physics', 'Biology', 'English'] },
  { name: 'Student46', subjects: ['Psychology', 'Sculpture', 'Spanish', 'French', 'Painting'] },
  { name: 'Student47', subjects: ['Biology', 'Computer Science', 'Physics', 'Economics', 'Geography'] },
  { name: 'Student48', subjects: ['Music', 'Physical Education', 'Physics', 'Political Science', 'Painting', 'Literature', 'Spanish'] },
  { name: 'Student49', subjects: ['French', 'Psychology', 'Political Science', 'Sculpture', 'Spanish', 'Art', 'Philosophy', 'Music', 'Painting'] },
  { name: 'Student50', subjects: ['Economics', 'Biology', 'English', 'Physics', 'Maths', 'Geography', 'Computer Science', 'Literature', 'History'] },
  { name: 'Student51', subjects: ['Physical Education', 'Psychology', 'Sculpture', 'Spanish', 'Painting', 'Philosophy'] },
  { name: 'Student52', subjects: ['Sculpture', 'Music', 'Physical Education', 'Political Science', 'French', 'Spanish', 'Art', 'Philosophy', 'Painting', 'Psychology'] },
  { name: 'Student53', subjects: ['Philosophy', 'French', 'Music', 'Painting', 'Art'] },
  { name: 'Student54', subjects: ['Maths', 'Geography', 'Economics'] },
  { name: 'Student55', subjects: ['Spanish', 'Philosophy', 'Political Science', 'Music', 'Sculpture'] },
  { name: 'Student56', subjects: ['Economics', 'Maths', 'Biology', 'Computer Science'] },
  { name: 'Student57', subjects: ['French', 'Psychology', 'Art', 'Sculpture', 'Spanish', 'Physical Education', 'Philosophy', 'Music', 'Painting', 'Political Science'] },
  { name: 'Student58', subjects: ['Political Science', 'Spanish', 'Physical Education', 'Sculpture', 'Art', 'Psychology', 'Painting'] },
  { name: 'Student59', subjects: ['Geography', 'Psychology', 'Sculpture', 'Philosophy', 'Music', 'Chemistry', 'Literature', 'Biology', 'Computer Science'] },
  { name: 'Student60', subjects: ['Biology', 'English', 'History', 'Literature', 'Maths'] },
  { name: 'Student61', subjects: ['Computer Science', 'English', 'Biology', 'Maths', 'Geography', 'Physics', 'Literature'] },
  { name: 'Student62', subjects: ['French', 'Political Science', 'Physical Education', 'Psychology', 'Music', 'Art', 'Painting', 'Spanish', 'Sculpture'] },
  { name: 'Student63', subjects: ['Geography', 'Computer Science', 'History', 'Economics'] },
  { name: 'Student64', subjects: ['History', 'Music', 'Physics', 'Painting', 'Political Science', 'Literature', 'Computer Science', 'Sculpture', 'Chemistry'] },
  { name: 'Student65', subjects: ['Maths', 'English', 'Physics', 'Economics', 'Biology', 'Literature', 'Geography', 'Chemistry', 'History', 'Computer Science'] },
  { name: 'Student66', subjects: ['Economics', 'Computer Science', 'Biology', 'Physics'] },
  { name: 'Student67', subjects: ['English', 'Geography', 'Chemistry', 'Literature', 'Physics', 'Maths', 'Biology', 'History', 'Economics', 'Computer Science'] },
  { name: 'Student68', subjects: ['Literature', 'Chemistry', 'History', 'Biology', 'Economics', 'Computer Science', 'Physics'] },
  { name: 'Student69', subjects: ['Biology', 'Chemistry', 'Geography', 'Maths', 'Literature'] },
  { name: 'Student70', subjects: ['Sculpture', 'Philosophy', 'Music', 'Psychology', 'Art', 'Physical Education', 'Political Science'] },
  { name: 'Student71', subjects: ['Maths', 'Literature', 'Chemistry', 'Physics', 'Computer Science'] },
  { name: 'Student72', subjects: ['Literature', 'Maths', 'Geography', 'Computer Science', 'History', 'Physics', 'Economics', 'Biology'] },
  { name: 'Student73', subjects: ['History', 'Maths', 'Computer Science'] },
  { name: 'Student74', subjects: ['Maths', 'History', 'Chemistry', 'Literature', 'Geography'] },
  { name: 'Student75', subjects: ['Political Science', 'Spanish', 'Sculpture', 'Physical Education', 'Philosophy', 'Painting', 'French', 'Art', 'Music'] },
  { name: 'Student76', subjects: ['Psychology', 'Art', 'French', 'Philosophy'] },
  { name: 'Student77', subjects: ['French', 'Music', 'Philosophy'] },
  { name: 'Student78', subjects: ['Computer Science', 'Maths', 'Literature', 'Economics', 'Physics', 'History', 'English', 'Biology', 'Chemistry'] },
  { name: 'Student79', subjects: ['English', 'Geography', 'Literature', 'History'] },
  { name: 'Student80', subjects: ['Literature', 'Maths', 'Computer Science', 'Physics', 'Economics', 'Chemistry'] },
  { name: 'Student81', subjects: ['English', 'Literature', 'Geography', 'Physics', 'Economics', 'Chemistry', 'Biology'] },
  { name: 'Student82', subjects: ['Sculpture', 'Spanish', 'Music', 'Philosophy', 'Physical Education', 'Political Science', 'Art', 'Painting', 'Psychology'] },
  { name: 'Student83', subjects: ['Geography', 'Maths', 'Biology', 'Computer Science'] },
  { name: 'Student84', subjects: ['Art', 'Painting', 'Spanish', 'Sculpture', 'Music', 'Philosophy', 'Physical Education'] },
  { name: 'Student85', subjects: ['Literature', 'History', 'Sculpture', 'Music', 'Philosophy', 'Art', 'Painting', 'Economics', 'Biology'] },
  { name: 'Student86', subjects: ['Painting', 'Sculpture', 'Physical Education', 'Art', 'Music'] },
  { name: 'Student87', subjects: ['Economics', 'Maths', 'Literature', 'Physics', 'History'] },
  { name: 'Student88', subjects: ['Painting', 'Philosophy', 'Physical Education', 'Political Science', 'Sculpture', 'Psychology', 'Spanish'] },
  { name: 'Student89', subjects: ['Psychology', 'Painting', 'Spanish'] },
  { name: 'Student90', subjects: ['Political Science', 'Music', 'Biology', 'Spanish', 'Physics'] },
  { name: 'Student91', subjects: ['Philosophy', 'Psychology', 'French', 'Music', 'Spanish', 'Painting'] },
  { name: 'Student92', subjects: ['Physical Education', 'Art', 'French', 'Psychology', 'Sculpture'] },
  { name: 'Student93', subjects: ['Biology', 'Geography', 'Literature', 'Physics', 'History'] },
  { name: 'Student94', subjects: ['English', 'Geography', 'Computer Science', 'Literature', 'Chemistry', 'History', 'Physics', 'Biology', 'Economics', 'Maths'] },
  { name: 'Student95', subjects: ['History', 'Economics', 'English', 'Chemistry', 'Computer Science', 'Geography', 'Physics', 'Literature', 'Biology', 'Maths'] },
  { name: 'Student96', subjects: ['Physics', 'Economics', 'Chemistry', 'Geography', 'Biology', 'Literature', 'Computer Science'] },
  { name: 'Student97', subjects: ['Spanish', 'French', 'Art', 'Painting', 'Political Science', 'Sculpture', 'Philosophy', 'Music'] },
  { name: 'Student98', subjects: ['Music', 'Physics', 'Sculpture', 'Economics', 'Literature', 'Geography', 'English', 'Computer Science', 'Biology'] },
  { name: 'Student99', subjects: ['History', 'Economics', 'Literature', 'Physics', 'Maths', 'English', 'Biology'] },
  { name: 'Student100', subjects: ['Geography', 'English', 'Maths'] },
  { name: 'Student101', subjects: ['Computer Science', 'Art', 'History', 'Geography', 'Biology', 'Painting', 'Physical Education', 'Philosophy', 'Psychology'] },
  { name: 'Student102', subjects: ['Economics', 'Literature', 'Maths', 'History', 'Physics', 'Chemistry', 'Geography'] },
  { name: 'Student103', subjects: ['Painting', 'Psychology', 'French', 'Spanish', 'Physical Education'] },
  { name: 'Student104', subjects: ['Art', 'Sculpture', 'Physical Education', 'Biology', 'Chemistry', 'Literature', 'Physics', 'Painting', 'Spanish', 'Economics'] },
  { name: 'Student105', subjects: ['Philosophy', 'Physical Education', 'Sculpture', 'Psychology', 'French', 'Music', 'Art', 'Spanish', 'Political Science'] },
  { name: 'Student106', subjects: ['Sculpture', 'Spanish', 'Chemistry', 'Physics'] },
  { name: 'Student107', subjects: ['Art', 'Philosophy', 'Psychology', 'Music', 'Political Science', 'Painting', 'Sculpture', 'Physical Education', 'French'] },
  { name: 'Student108', subjects: ['History', 'Biology', 'Economics', 'Geography', 'Literature'] },
  { name: 'Student109', subjects: ['Political Science', 'Spanish', 'Music'] },
  { name: 'Student110', subjects: ['Physics', 'Maths', 'Literature'] },
  { name: 'Student111', subjects: ['French', 'Spanish', 'Painting', 'Physical Education', 'Sculpture', 'Psychology', 'Philosophy'] },
  { name: 'Student112', subjects: ['Physics', 'Literature', 'Geography', 'History', 'Computer Science', 'English', 'Economics'] },
  { name: 'Student113', subjects: ['Geography', 'Physics', 'Economics', 'Literature', 'English', 'Maths'] },
  { name: 'Student114', subjects: ['Physical Education', 'Philosophy', 'Political Science', 'French', 'Art', 'Painting', 'Sculpture', 'Spanish', 'Music', 'Psychology'] },
  { name: 'Student115', subjects: ['Physics', 'Maths', 'Economics', 'History', 'Literature'] },
  { name: 'Student116', subjects: ['Biology', 'Literature', 'Economics', 'Chemistry', 'Computer Science'] },
  { name: 'Student117', subjects: ['Philosophy', 'Art', 'Political Science', 'Music', 'Painting', 'French'] },
  { name: 'Student118', subjects: ['Music', 'Economics', 'Maths', 'Literature', 'Political Science', 'French', 'Art', 'Geography', 'History', 'Psychology'] },
  { name: 'Student119', subjects: ['Biology', 'Maths', 'Physics', 'Economics', 'Literature'] },
  { name: 'Student120', subjects: ['Geography', 'Maths', 'History', 'Physics', 'Computer Science', 'English', 'Biology', 'Literature'] },
  { name: 'Student121', subjects: ['Biology', 'Economics', 'Physics', 'Chemistry', 'English', 'Literature', 'History'] },
  { name: 'Student122', subjects: ['Philosophy', 'Psychology', 'Physical Education', 'Spanish', 'Music', 'Painting'] },
  { name: 'Student123', subjects: ['English', 'Economics', 'Physics'] },
  { name: 'Student124', subjects: ['Philosophy', 'Spanish', 'Art', 'Sculpture'] },
  { name: 'Student125', subjects: ['Literature', 'Chemistry', 'Geography', 'English', 'Biology', 'Computer Science', 'Economics', 'Maths', 'History', 'Physics'] },
  { name: 'Student126', subjects: ['Chemistry', 'English', 'History'] },
  { name: 'Student127', subjects: ['French', 'Painting', 'Sculpture', 'Music', 'Spanish', 'Psychology', 'Political Science', 'Art', 'Physical Education', 'Philosophy'] },
  { name: 'Student128', subjects: ['French', 'Political Science', 'Music', 'Psychology', 'Art'] },
  { name: 'Student129', subjects: ['English', 'Literature', 'Biology', 'Geography', 'Economics'] },
  { name: 'Student130', subjects: ['Music', 'Political Science', 'Philosophy', 'French', 'Sculpture', 'Psychology', 'Spanish'] },
  { name: 'Student131', subjects: ['Art', 'Philosophy', 'Political Science', 'Physical Education', 'French', 'Psychology', 'Sculpture', 'Spanish'] },
  { name: 'Student132', subjects: ['Chemistry', 'Maths', 'History', 'Computer Science', 'Biology', 'Literature', 'Economics', 'Geography'] },
  { name: 'Student133', subjects: ['Philosophy', 'Political Science', 'Physical Education', 'Psychology', 'French', 'Spanish', 'Sculpture', 'Music'] },
  { name: 'Student134', subjects: ['History', 'Maths', 'Physics', 'English', 'Computer Science'] },
  { name: 'Student135', subjects: ['Physical Education', 'Political Science', 'Spanish', 'Art', 'Painting', 'Philosophy'] },
  { name: 'Student136', subjects: ['Political Science', 'Philosophy', 'Physical Education'] },
  { name: 'Student137', subjects: ['Art', 'Physical Education', 'Painting', 'Sculpture', 'Philosophy', 'Psychology', 'Music'] },
  { name: 'Student138', subjects: ['Geography', 'Economics', 'Computer Science', 'History'] },
  { name: 'Student139', subjects: ['Philosophy', 'Psychology', 'Art', 'Physical Education', 'French', 'Political Science', 'Sculpture', 'Music', 'Painting'] },
  { name: 'Student140', subjects: ['Music', 'Psychology', 'French', 'Painting', 'Political Science', 'Art', 'Sculpture', 'Spanish'] },
  { name: 'Student141', subjects: ['Geography', 'Economics', 'Computer Science', 'Biology', 'Maths', 'Literature'] },
  { name: 'Student142', subjects: ['Music', 'Spanish', 'Painting', 'Philosophy', 'Physical Education', 'Sculpture', 'French'] },
  { name: 'Student143', subjects: ['Spanish', 'Music', 'Sculpture', 'Psychology', 'Physical Education', 'Political Science'] },
  { name: 'Student144', subjects: ['Music', 'Philosophy', 'Art', 'Psychology', 'Physical Education', 'French', 'Spanish', 'Political Science', 'Painting', 'Sculpture'] },
  { name: 'Student145', subjects: ['Chemistry', 'Computer Science', 'History', 'Biology', 'Geography', 'English'] },
  { name: 'Student146', subjects: ['Philosophy', 'Psychology', 'Physical Education', 'French', 'Painting', 'Art', 'Music'] },
  { name: 'Student147', subjects: ['Psychology', 'Biology', 'Philosophy'] },
  { name: 'Student148', subjects: ['English', 'Biology', 'Literature', 'Geography', 'Computer Science', 'Economics', 'Physics', 'Chemistry', 'Maths', 'History'] },
  { name: 'Student149', subjects: ['Painting', 'Art', 'Sculpture'] },
  { name: 'Student150', subjects: ['Computer Science', 'Art', 'French'] },
  { name: 'Student151', subjects: ['Economics', 'English', 'Chemistry', 'Literature'] },
  { name: 'Student152', subjects: ['Music', 'Painting', 'Psychology', 'Philosophy', 'Spanish', 'Art'] },
  { name: 'Student153', subjects: ['Geography', 'History', 'Economics'] },
  { name: 'Student154', subjects: ['Economics', 'Physics', 'History', 'Biology', 'Maths', 'Computer Science', 'Chemistry', 'Literature', 'Geography'] },
  { name: 'Student155', subjects: ['Psychology', 'Sculpture', 'Physical Education', 'Philosophy', 'Political Science', 'Art', 'French'] },
  { name: 'Student156', subjects: ['Physics', 'Maths', 'Biology', 'English'] },
  { name: 'Student157', subjects: ['French', 'Spanish', 'Psychology'] },
  { name: 'Student158', subjects: ['Economics', 'History', 'Maths', 'Biology', 'Geography', 'Chemistry', 'English', 'Literature', 'Computer Science', 'Physics'] },
  { name: 'Student159', subjects: ['Physical Education', 'Sculpture', 'Painting', 'Spanish', 'Art', 'Psychology'] },
  { name: 'Student160', subjects: ['Music', 'Philosophy', 'Painting', 'Spanish', 'Sculpture', 'Psychology'] },
  { name: 'Student161', subjects: ['History', 'Physics', 'Biology', 'Economics', 'Literature'] },
  { name: 'Student162', subjects: ['Philosophy', 'Art', 'Music', 'Psychology'] },
  { name: 'Student163', subjects: ['Music', 'Painting', 'Philosophy', 'Political Science', 'Spanish', 'French', 'Physical Education'] },
  { name: 'Student164', subjects: ['Art', 'Sculpture', 'Physical Education', 'Music', 'Psychology', 'Spanish', 'French'] },
  { name: 'Student165', subjects: ['Physical Education', 'Political Science', 'French', 'Painting', 'Music', 'Sculpture', 'Psychology', 'Art', 'Philosophy', 'Spanish'] },
  { name: 'Student166', subjects: ['Physical Education', 'Music', 'Painting', 'Psychology'] },
  { name: 'Student167', subjects: ['Sculpture', 'Spanish', 'Political Science', 'Physical Education', 'Painting', 'French'] },
  { name: 'Student168', subjects: ['Biology', 'Maths', 'Physics', 'Computer Science', 'History', 'Economics'] },
  { name: 'Student169', subjects: ['Biology', 'Maths', 'Chemistry', 'Geography', 'Economics', 'English', 'Physics', 'Computer Science', 'History', 'Literature'] },
  { name: 'Student170', subjects: ['Biology', 'Economics', 'Computer Science', 'Chemistry', 'English', 'Physics'] },
  { name: 'Student171', subjects: ['Painting', 'Psychology', 'Music', 'French', 'Physical Education', 'Spanish', 'Art'] },
  { name: 'Student172', subjects: ['Maths', 'Philosophy', 'Economics', 'Sculpture', 'Spanish', 'Biology', 'Computer Science', 'Physical Education'] },
  { name: 'Student173', subjects: ['Sculpture', 'Maths', 'Spanish', 'Physical Education', 'Economics', 'Art', 'Philosophy', 'Psychology'] },
  { name: 'Student174', subjects: ['Sculpture', 'French', 'Painting', 'Political Science', 'Art', 'Music', 'Philosophy', 'Psychology'] },
  { name: 'Student175', subjects: ['Music', 'Art', 'Biology', 'Chemistry', 'History'] },
  { name: 'Student176', subjects: ['History', 'English', 'Maths', 'Geography', 'Chemistry', 'Economics', 'Biology'] },
  { name: 'Student177', subjects: ['Maths', 'Chemistry', 'Economics', 'History', 'Physics', 'Literature', 'Geography', 'English'] },
  { name: 'Student178', subjects: ['Computer Science', 'Economics', 'Geography', 'Biology', 'History', 'English', 'Chemistry', 'Maths', 'Physics', 'Literature'] },
  { name: 'Student179', subjects: ['History', 'Biology', 'Chemistry', 'English'] },
  { name: 'Student180', subjects: ['Literature', 'Economics', 'English', 'Geography', 'Maths', 'Physics', 'History', 'Biology', 'Chemistry'] },
  { name: 'Student181', subjects: ['French', 'Spanish', 'Art', 'Psychology', 'Sculpture', 'Painting', 'Political Science', 'Philosophy'] },
  { name: 'Student182', subjects: ['Painting', 'Sculpture', 'French', 'Philosophy', 'Psychology', 'Physical Education'] },
  { name: 'Student183', subjects: ['Physical Education', 'Music', 'Philosophy', 'Painting', 'Psychology', 'Political Science', 'Art', 'Sculpture', 'French', 'Spanish'] },
  { name: 'Student184', subjects: ['Computer Science', 'English', 'Geography'] },
  { name: 'Student185', subjects: ['Music', 'Political Science', 'Sculpture'] },
  { name: 'Student186', subjects: ['Music', 'Philosophy', 'Political Science', 'Psychology', 'French', 'Painting', 'Sculpture', 'Art', 'Spanish', 'Physical Education'] },
  { name: 'Student187', subjects: ['Physics', 'English', 'Literature', 'History', 'Computer Science', 'Geography'] },
  { name: 'Student188', subjects: ['Physics', 'Literature', 'Geography', 'English', 'History', 'Computer Science', 'Biology', 'Maths', 'Chemistry'] },
  { name: 'Student189', subjects: ['Art', 'Philosophy', 'Spanish', 'Music'] },
  { name: 'Student190', subjects: ['Chemistry', 'Literature', 'English'] },
  { name: 'Student191', subjects: ['History', 'Geography', 'Chemistry', 'French', 'Philosophy', 'Painting'] },
  { name: 'Student192', subjects: ['Psychology', 'Music', 'Painting'] },
  { name: 'Student193', subjects: ['Computer Science', 'Physics', 'Literature', 'History', 'Chemistry', 'Biology', 'Maths'] },
  { name: 'Student194', subjects: ['English', 'Computer Science', 'Literature', 'Geography', 'Biology', 'Maths'] },
  { name: 'Student195', subjects: ['History', 'Economics', 'Geography', 'Physics', 'Biology', 'Maths', 'Computer Science'] },
  { name: 'Student196', subjects: ['Economics', 'Biology', 'Physics', 'English', 'Geography', 'Computer Science', 'Maths', 'History', 'Literature'] },
  { name: 'Student197', subjects: ['Computer Science', 'Physics', 'Literature', 'Chemistry', 'History', 'English'] },
  { name: 'Student198', subjects: ['Literature', 'English', 'History', 'Economics', 'Chemistry', 'Geography', 'Biology'] },
  { name: 'Student199', subjects: ['English', 'Economics', 'History', 'Geography', 'Chemistry', 'Physics', 'Literature', 'Computer Science'] },
  { name: 'Student200', subjects: ['Literature', 'Chemistry', 'History', 'Geography', 'English', 'Physics', 'Computer Science', 'Maths', 'Biology', 'Economics'] },
  { name: 'Student201', subjects: ['Geography', 'Maths', 'English', 'Physics'] },
  { name: 'Student202', subjects: ['History', 'Spanish', 'Music', 'Philosophy', 'French', 'Psychology', 'Computer Science', 'English'] },
  { name: 'Student203', subjects: ['Economics', 'Physics', 'History', 'English', 'Biology', 'Maths', 'Literature', 'Chemistry'] },
  { name: 'Student204', subjects: ['Physics', 'Economics', 'Literature', 'Chemistry', 'History', 'Geography', 'Biology'] },
  { name: 'Student205', subjects: ['Political Science', 'Philosophy', 'Psychology', 'Painting', 'Music', 'Physical Education', 'Art', 'French', 'Sculpture'] },
  { name: 'Student206', subjects: ['Geography', 'Maths', 'Computer Science', 'English'] },
  { name: 'Student207', subjects: ['Political Science', 'French', 'Psychology', 'Painting', 'Spanish', 'Philosophy', 'Sculpture', 'Music', 'Art', 'Physical Education'] },
  { name: 'Student208', subjects: ['Physical Education', 'Political Science', 'Sculpture', 'Painting', 'French', 'Spanish', 'Music', 'Art'] },
  { name: 'Student209', subjects: ['French', 'Spanish', 'Music', 'Art', 'Painting', 'Psychology', 'Philosophy'] },
  { name: 'Student210', subjects: ['Spanish', 'Philosophy', 'Art', 'Painting', 'Political Science', 'Sculpture', 'Music', 'Physical Education', 'Psychology', 'French'] },
  { name: 'Student211', subjects: ['French', 'Political Science', 'Psychology', 'Physical Education', 'Music', 'Spanish', 'Painting', 'Philosophy'] },
  { name: 'Student212', subjects: ['Physics', 'Economics', 'English'] },
  { name: 'Student213', subjects: ['Economics', 'Geography', 'Computer Science', 'Chemistry', 'History', 'Physics'] },
  { name: 'Student214', subjects: ['English', 'Painting', 'Physical Education', 'Psychology', 'Spanish', 'Philosophy'] },
  { name: 'Student215', subjects: ['Literature', 'Maths', 'English'] },
  { name: 'Student216', subjects: ['Psychology', 'Painting', 'Physical Education', 'Art'] },
  { name: 'Student217', subjects: ['History', 'Maths', 'Physics', 'Economics', 'Geography', 'Literature', 'Computer Science', 'English', 'Biology', 'Chemistry'] },
  { name: 'Student218', subjects: ['Psychology', 'Sculpture', 'Music', 'Painting', 'Physical Education', 'Art'] },
  { name: 'Student219', subjects: ['Literature', 'Maths', 'Physics', 'Chemistry', 'History', 'Geography', 'Biology', 'English'] },
  { name: 'Student220', subjects: ['History', 'Computer Science', 'Geography', 'Biology', 'Chemistry'] },
  { name: 'Student221', subjects: ['Psychology', 'Physical Education', 'Political Science', 'Spanish', 'Music', 'French', 'Philosophy'] },
  { name: 'Student222', subjects: ['Music', 'Political Science', 'Physical Education'] },
  { name: 'Student223', subjects: ['Geography', 'Biology', 'English', 'Chemistry', 'Economics'] },
  { name: 'Student224', subjects: ['Sculpture', 'Spanish', 'Biology', 'Painting', 'English', 'Art', 'Physical Education', 'Political Science', 'Psychology', 'Philosophy'] },
  { name: 'Student225', subjects: ['French', 'Sculpture', 'Psychology', 'Art', 'Spanish', 'Painting', 'Physical Education', 'Political Science', 'Music'] },
  { name: 'Student226', subjects: ['Geography', 'Computer Science', 'History', 'Economics'] },
  { name: 'Student227', subjects: ['Painting', 'Music', 'Philosophy', 'Psychology'] },
  { name: 'Student228', subjects: ['Economics', 'History', 'Computer Science', 'Chemistry', 'Maths', 'Biology', 'Geography', 'Physics', 'English', 'Literature'] },
  { name: 'Student229', subjects: ['Spanish', 'Geography', 'Biology'] },
  { name: 'Student230', subjects: ['Computer Science', 'Literature', 'English', 'Chemistry'] },
  { name: 'Student231', subjects: ['Biology', 'Computer Science', 'Literature', 'Physics'] },
  { name: 'Student232', subjects: ['Biology', 'Chemistry', 'Geography', 'Economics', 'Computer Science', 'English', 'History', 'Maths', 'Literature'] },
  { name: 'Student233', subjects: ['Economics', 'Spanish', 'Philosophy', 'Music', 'Sculpture', 'French', 'Psychology', 'Maths', 'Geography'] },
  { name: 'Student234', subjects: ['Literature', 'Biology', 'Maths', 'Geography', 'Computer Science', 'Economics', 'Physics', 'Chemistry'] },
  { name: 'Student235', subjects: ['Physics', 'Chemistry', 'Maths', 'Geography', 'History', 'Literature', 'Computer Science', 'Economics'] },
  { name: 'Student236', subjects: ['Psychology', 'Computer Science', 'Sculpture', 'Spanish', 'Philosophy', 'Economics', 'Physical Education'] },
  { name: 'Student237', subjects: ['Economics', 'Computer Science', 'English'] },
  { name: 'Student238', subjects: ['Music', 'Art', 'Sculpture'] },
  { name: 'Student239', subjects: ['Philosophy', 'Sculpture', 'Art', 'French', 'Geography', 'English'] },
  { name: 'Student240', subjects: ['History', 'Economics', 'Physics', 'Chemistry', 'Literature', 'Maths', 'Computer Science', 'Biology', 'English', 'Geography'] },
  { name: 'Student241', subjects: ['Maths', 'Literature', 'Philosophy', 'English', 'Spanish'] },
  { name: 'Student242', subjects: ['French', 'Art', 'Political Science', 'Psychology', 'Painting', 'Philosophy', 'Spanish', 'Physical Education', 'Music', 'Sculpture'] },
  { name: 'Student243', subjects: ['Art', 'Philosophy', 'Sculpture', 'French'] },
  { name: 'Student244', subjects: ['Sculpture', 'Political Science', 'Physical Education', 'French', 'Psychology', 'Art', 'Spanish', 'Philosophy', 'Painting'] },
  { name: 'Student245', subjects: ['Physics', 'Economics', 'Literature', 'Computer Science'] },
  { name: 'Student246', subjects: ['Biology', 'Computer Science', 'English', 'Economics', 'Physics', 'Literature', 'Maths', 'History', 'Chemistry'] },
  { name: 'Student247', subjects: ['Philosophy', 'Art', 'Music', 'Psychology', 'Sculpture', 'French', 'Physical Education', 'Spanish'] },
  { name: 'Student248', subjects: ['Spanish', 'Music', 'Art', 'French', 'Sculpture', 'Painting', 'Political Science', 'Physical Education', 'Psychology'] },
  { name: 'Student249', subjects: ['Psychology', 'Art', 'Political Science', 'Painting', 'Philosophy', 'Physical Education'] },
  { name: 'Student250', subjects: ['Maths', 'Economics', 'Chemistry', 'Computer Science', 'Geography'] },
];

// Pour l'approche gloutonne
console.log('Greedy approach');
const greedySchedule = scheduleExamsGreedy(subjects, students);

// Pour l'approche génétique
console.log('Genetic approach');
const geneticSchedule = scheduleExamsGenetic(subjects, students, 300, 10000, 0.1);